### PR TITLE
otp-insert: require only one of `--issuer` or `--account`

### LINKED ISSUE #68: `insert` without BOTH `--issuer` and `--account` fails with error message stating either one is required
**pass-otp-insert help text**

```
pass otp insert [--force,-f] [--echo,-e]
        [[--secret, -s] [--issuer,-i issuer] [--account,-a account]]
        [pass-name]
    Prompt for and insert a new OTP key.

    If 'secret' is specified, prompt for the OTP secret, assuming SHA1
    algorithm, 30-second period, and 6 OTP digits; one of 'issuer' or
    'account' is also required. Otherwise, prompt for a key URI; if
    'pass-name' is not supplied, use the URI label.

    Optionally, echo the input. Prompt before overwriting existing URI
    unless forced. This command accepts input from stdin.
```

Emphasis on the following: **`one of 'issuer' or 'account' is also required`**. That statement seems to be inaccurate - see the following:

```
$ pass otp insert --secret --account me@domain.com test
Missing issuer or account
```

```
$ pass otp insert --secret -a me@domain.com test
Missing issuer or account
```

### PR DESCRIPTION
**Pull request by bddenhartog**
closes #68

### CODE REVIEW

**Comment by bddenhartog** [comment]
I'll be force-pushing changes across to my branch; working through adding conditional support for both of them at the moment.

**Comment by lanodan** [comment]
It looks like there is a typo on ``seperator`` it should be ``separator`` or something like ``insert_separator`` if there is some conflict.

**Comment by bddenhartog** [comment]
@lanodan Good catch. The commit has been amended to fix the typo.

**Comment by bddenhartog** [comment]
@tadfisher, what is your general release cycle?

**Pull request merged**
